### ISSUE TITLE
Artifact of Chaos, consumables

### ISSUE THREAD

**Issue by AJ9844** [peterbozso/ror2arena#2]
Some quality of life additions to maybe consider:

1, Adding some way to either prevent or replenish consumable items (Delicate Watch ect...) so that you dont just lose all of your stuff to the battle with friends.
2, Disabling the Chaos Artifact AFTER the remaining players have been killed. I've come across many times where i would die to my own items/abilities after the Arena fight.

Just some possible suggestions. Other than that, very fun mod, Keep up the good work :)

**Comment by peterbozso** [comment]
Thank you very much for reaching out!

These are both very good ideas. I've added them to [the backlog.](https://github.com/users/peterbozso/projects/1/views/1) ("Consumables" and "Artifact of Chaos" respectively.)

As you can see, currently I am working on the item drops feature, but right after that is finished, I'll look into the question of Artifact of Chaos. I am thinking about completely dropping that and implementing PvP myself, since it's self-damage component can be a big handicap for melee survivors.

Thanks again for your feedback and I am very happy to see you are having a good time with my mod! :)

I'll rename this issue and keep it open, in case somebody else will have feedback on these ideas too.

**Comment by peterbozso** [comment]
Nevermind, I created a separate issue for Artifact of Chaos #4 and I will keep the consumables one in the backlog for now as an idea. Closing this one in favor of those.
